query Feed($skip: Int, $filter: String) {
  videos(
    filter: $filter
    skip: $skip
    take: 25
    sortBy: { publishedAt: desc }
  ) {
    id
    snippet {
      id
      title
      description
      publishedAt
      thumbnailUrl
      channel {
        id
        snippet {
          title
          thumbnailUrl
        }
      }
    }
    contentDetails {
      id
      duration
      hasCaption
    }
    statistics {
      viewCount
      likeCount
      commentCount
    }
  }
}
